export const FEEDBACK_ADD_FILE = 'FEEDBACK_ADD_FILE';
export const FEEDBACK_INITIAL_FORM = 'FEEDBACK_INITIAL_FORM';
export const FEEDBACK_LOADING = 'FEEDBACK_LOADING';
export const FEEDBACK_ERROR = 'FEEDBACK_ERROR';
export const FEEDBACK_REMOVE_FILE = 'FEEDBACK_REMOVE_FILE'; 
export const FEEDBACK_SUCCESS = 'FEEDBACK_SUCCESS';
export const FEEDBACK_UPDATE_FORM = 'FEEDBACK_UPDATE_FORM';